# -*- coding: utf-8 -*-
{
    'name': 'PATCO Equipment (FSM)',
    'version': '18.0.1.0.0',
    'summary': 'Equipment extensions integrated in Field Service',
    'author': 'PATCO',
    'website': 'https://www.patco.pe',
    'license': 'LGPL-3',
    'depends': [
        'base',
        'maintenance',
        'base_maintenance',
        #'base_maintenance_group',
        'maintenance_equipment_category_hierarchy',
        'base_territory',
        'fieldservice',
        'fieldservice_stock',
        'fieldservice_agreement',
        'fieldservice_activity',
        #'fieldservice_kanban_info',
        'fieldservice_calendar',
        'fieldservice_sale',
        'fieldservice_sale_agreement',
        'fieldservice_repair',
        #'patco_manuales',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/sequences.xml',
        'views/maintenance_equipment_views.xml',
        #'views/maintenance_equipment_category_views.xml',
        'wizards/assign_equipment_wizard_views.xml',
        'views/fsm_order_views.xml',
        'views/maintenance_request_views.xml',
        'views/mobile_views.xml',
        'views/fsm_leader_views.xml',
        'views/fsm_order_form_labels.xml',
    ],
    'demo': [],
    'assets': {},
    'installable': True,
    'auto_install': False,
    'application': False,
}